version: '2'
services:
  rails:
    build:
      context: ./services/rails
      dockerfile: Dockerfile
    volumes:
      - ./app:/mnt/app
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
volumes:
  db:
    driver: local
